/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'nick' at '10/7/16 7:53 PM' with Gradle 3.1
 *
 * @author nick, @date 10/7/16 7:53 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
