/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'nick' at '10/7/16 7:53 PM' with Gradle 3.1
 *
 * @author nick, @date 10/7/16 7:53 PM
 */

import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    assert(true)
  }
}
